### ISSUE TITLE
proxy to nex protocol?

### ISSUE THREAD

**Issue by d47081** [omar-polo/gmid#27]
Hello, can I setup the upstream located at `nex` protocol?

**Comment by omar-polo** [comment]
I don't know the `nex` protocol, so probably not.  The proxy facility only supports gemini and gemini-without-tls (which is not a proper protocol but in practice it can be useful.)

Can you share a link to a page describing the protocol?

Thanks!

**Comment by omar-polo** [comment]
Oh, interesting.  This protocol went under my radar :)

Upon a quick look it seems like adding support for it will be very easy (easier than #23 for sure :p).  I just have a few doubts/questions open:

 - as far as I'm seeing, if the path terminates with "/" we can assume it's a directory listing, so we can serve it as "text/gemini" ?
 - what do we use for the mime type?  As far as i can see, we don't know the content of the response, so we'll have to guess?  Maybe if there are no NUL bytes in the first `n` bytes we can serve it as text/plain, and application/octet-stream otherwise?

**Comment by omar-polo** [comment]
Ah I see.  Maybe we can even re-use gmid' built-in mime types for this.

**Comment by omar-polo** [comment]
Yeah, if the intention is to just forward the connection to a specific backend then a dedicated daemon like relayd, haproxy or even nginx is probably better.

I don't think it would be a good move for gmid to become capable of proxy random data, it's not designed for that.  There are better options for that.

What I think could be worthwhile, although i'm still a bit undecided, if it could make sense to use gmid to proxy/convert other protocols to gemini.  So that it can be used to make available nex:// pages from gemini://, or like proposed in #23 to fetch content via http and serve it via gemini.
