### ISSUE TITLE
Official docker/OCI container

### ISSUE THREAD

**Issue by ivanov17** [omar-polo/gmid#29]
Is there any plans to provide an official docker/OCI container for gmid?

Thank you.

**Comment by omar-polo** [comment]
great timing, i was just thinking to add a workflow to publish an image to the github registry.  would that work for you?

**Comment by omar-polo** [comment]
I've added a new workflow that pushes an image to the github registry, it should be publicly available, see <https://github.com/omar-polo/gmid/pkgs/container/gmid>.

unfortunately out-of-the-box it's not really useful, since it contains a self-signed cert for "localhost", but if new certs are mounted over it could work.  

I'm open to any suggestions to improve the default image :)

**Comment by ivanov17** [comment]
Thank you very much! I'll try it soon. If I have any ideas, I'll write to you and try to create a pull request.

**Comment by omar-polo** [comment]
will count on it ;)

I'm going to close this as completed then, thanks
