### ISSUE TITLE
Configuration for a tilde server?

### ISSUE THREAD

**Issue by hatdropper1977** [omar-polo/gmid#40]
I would like to create a *tilde server*.  So, if I have user **foobar**, he would upload docs into his **/home/foobar/public_capsules** directory, and then a reader can read the docs with URL **gemini://my.site/~foobar/**.  I would like the **gmid.conf** to have flexibility, so I can add additional users without needing to update the config.

**Comment by omar-polo** [comment]
Hello,

I'd suggest to avoid serving from user directories, since bugs in the server implementation could lead an attacker to access files on the users home directory they shouldn't see.  Instead, why not use `/var/gemini/~foobar` and have a symlink from `/home/foobar/public_capsules` to `/var/gemini/~foobar`?

This way, `/var/gemini` (or whatever other directory) can be exported as-is, gmid can be chrooted in there, and users still have the same experience.

HTH

**Comment by hatdropper1977** [comment]
Thank you - I linked it as above, but Gemini (chrooted) won't serve up the symlink.  Do you know of how I can configure it to follow symlinks?  

On apache we would do something like:

```bash
Options Indexes FollowSymLinks
```

**Comment by omar-polo** [comment]
Sorry, I meant the opposite: to store the user content in `/var/gemini/~username` and place a symlink in their home directory that points to `/var/gemini/~username`.  This way you get both the advantage of having it easy on the users, not needing to change the configuration every time a user is added (although gmid supports live-reloading for the configuration) and you have a secure set up with gmid chrooted.

**Comment by hatdropper1977** [comment]
That worked!  Thanks

**Comment by hatdropper1977** [comment]
Thank you, that works.
